api:
  key: "your_api_key"
  base: "https://api.feidaapi.com/v1"
  model: "openai/gpt-4o-mini"
  temperature: 0
  max_tokens: 5000


# api:
#   key: "your_api_key"
#   base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
#   model: "openai/qwen-plus"
#   temperature: 0
#   max_tokens: 5000